kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: deploytime-build-exporter
  namespace: pelorus
  labels:
    app: deploytime-build-exporter
    app.kubernetes.io/name: deploytime-build-exporter