kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: deploytime-build-exporter
  namespace: pelorus
  labels:
    app.kubernetes.io/name: deploytime-build-exporter
    application: deploytime-build-exporter
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - deploytime-build-exporter
        from:
          kind: ImageStreamTag
          namespace: pelorus
          name: 'deploytime-build-exporter:latest'
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: deploytime-build-exporter
    app.kubernetes.io/name: deploytime-build-exporter
    deploymentconfig: deploytime-build-exporter
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploytime-build-exporter
        app.kubernetes.io/name: deploytime-build-exporter
        application: deploytime-build-exporter
        deploymentconfig: deploytime-build-exporter
    spec:
      containers:
        - name: deploytime-build-exporter
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: APP_FILE
              value: deploytime/app.py
            - name: NAMESPACES
              value: 'coolstore-inventory-dev'
            - name: LOG_LEVEL
              value: DEBUG
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: pelorus-exporter
      serviceAccount: pelorus-exporter
      securityContext: {}
      schedulerName: default-scheduler