kind: Service
apiVersion: v1
metadata:
  name: committime-exporter
  namespace: pelorus
  labels:
    app.kubernetes.io/name: committime-exporter
    k8s-app: committime-exporter
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  selector:
    app.kubernetes.io/name: committime-exporter
    deploymentconfig: committime-exporter
