kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: committime-exporter
  namespace: pelorus
  labels:
    app.kubernetes.io/name: committime-exporter
    application: committime-exporter
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - committime-exporter
        from:
          kind: ImageStreamTag
          namespace: pelorus
          name: 'committime-exporter:latest'
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: committime-exporter
    app.kubernetes.io/name: committime-exporter
    deploymentconfig: committime-exporter
  template:
    metadata:
      labels:
        app: committime-exporter
        app.kubernetes.io/name: committime-exporter
        application: committime-exporter
        deploymentconfig: committime-exporter
    spec:
      containers:
        - name: committime-exporter
          env:
            - name: APP_FILE
              value: committime/app.py
            - name: NAMESPACES
              value: 'coolstore-inventory-cicd,coolstore-catalog-cicd'
            - name: LOG_LEVEL
              value: DEBUG
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: github-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: pelorus-exporter
      serviceAccount: pelorus-exporter
      securityContext: {}
      schedulerName: default-scheduler