kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: failure-exporter
  namespace: pelorus
  labels:
    app: failure-exporter
    app.kubernetes.io/name: failure-exporter
    application: failure-exporter
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'failure-exporter:latest'
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/python-39
  source:
    type: Git
    git:
      uri: 'https://github.com/adnan-drina/pelorus.git'
      ref: master
    contextDir: exporters
  triggers:
    - type: GitHub
      github:
        secretReference:
          name: github-secret
    - type: ConfigChange